# Generated by Django 3.1 on 2020-09-02 22:48

from django.db import migrations, models

def add_welcome_card(apps, schema_editor):
    ProfileCard = apps.get_model("blog", "ProfileCard")
    welcome_card = ProfileCard(name = 'Welcome')
    welcome_card.save()

def delete_all_cards(apps, schema_editor):
    ProfileCard = apps.get_model("blog", "ProfileCard")
    ProfileCard.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_welcome_card, delete_all_cards)
    ]
