# Generated by Django 3.1 on 2020-09-03 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200902_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilecard',
            name='desc',
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='current_profile_card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.profilecard'),
        ),
    ]
