# Generated by Django 3.1 on 2020-09-02 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200902_2147'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergallery',
            unique_together={('user', 'profile_card')},
        ),
    ]
