# Generated by Django 3.1 on 2020-08-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_bloguser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='desc',
            field=models.TextField(default='No description', max_length=250),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='hometown',
            field=models.CharField(default='Not specified', max_length=200),
        ),
    ]
