# Generated by Django 3.1 on 2020-08-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200820_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='user_id',
            new_name='followed',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='follower_id',
            new_name='follower',
        ),
    ]
