# Generated by Django 3.1 on 2020-08-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200820_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='email',
            field=models.EmailField(default='stupidemail@email.com', max_length=254, unique=True),
        ),
    ]
