# Generated by Django 3.1 on 2020-08-21 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200821_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='email',
        ),
    ]
