# Generated by Django 3.1 on 2020-08-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200824_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('img', models.ImageField(upload_to='profile_cards')),
            ],
        ),
        migrations.AddField(
            model_name='bloguser',
            name='current_profile_card_name',
            field=models.CharField(default='Welcome', max_length=50),
        ),
    ]
