# Generated by Django 3.1 on 2020-08-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200831_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecard',
            name='img_small',
            field=models.ImageField(default=0, upload_to='profile_cards_small'),
            preserve_default=False,
        ),
    ]
