# Generated by Django 3.1 on 2020-08-31 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_profilecard_img_small'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='current_profile_card',
        ),
    ]
