# Generated by Django 3.1 on 2020-08-31 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_bloguser_current_profile_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='current_profile_card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.profilecard'),
        ),
    ]
